# Generated by Django 4.2.7 on 2023-11-21 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('isAdmin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 11, 21, 10, 35, 30, 501550, tzinfo=datetime.timezone.utc))),
                ('updated', models.DateField(default=datetime.datetime(2023, 11, 21, 10, 35, 30, 501550, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
