# Generated by Django 4.2.7 on 2023-11-21 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_users_updated_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
