# Generated by Django 4.2.7 on 2023-11-21 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_teams_alter_users_created_alter_users_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 22, 37, 2, 373002)),
        ),
        migrations.AddField(
            model_name='teams',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 22, 37, 2, 373002)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 22, 37, 2, 373002)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 22, 37, 2, 373002)),
        ),
    ]
