# Generated by Django 4.2.7 on 2023-11-22 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_teams_created_teams_updated_alter_users_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teams'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 47, 6, 462870)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 47, 6, 462870)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 47, 6, 462870)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 47, 6, 462870)),
        ),
    ]
