# Generated by Django 4.2.7 on 2023-12-14 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_teams_created_alter_teams_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 21, 56, 3, 913189)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 21, 56, 3, 913189)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 21, 56, 3, 913189)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 21, 56, 3, 913189)),
        ),
    ]
