# Generated by Django 4.2.7 on 2023-12-14 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_teams_created_alter_teams_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 22, 23, 42, 440081, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 22, 23, 42, 440081, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 22, 23, 42, 441081, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 22, 23, 42, 441081, tzinfo=datetime.timezone.utc)),
        ),
    ]
